### PR TITLE
Update Japanese Strings

### PR DESCRIPTION
**Pull request by Jambalaya751955**

### CODE REVIEW

**Comment by purerosefallen** [comment]
JSON format is not correct at line 524.
Besides, there are many new lines rather than no-chat room.

**Comment by Jambalaya751955** [comment]
Thank you for your confrmination.
Yes sir. I will fix it.

**Comment by purerosefallen** [comment]
The missing strings are a bunch of challonge strings, and `disconnect_from_game`, and `reconnect_to_game`. It's advised to take a look of the history of `i18n.json`.

**Comment by Jambalaya751955** [comment]
I have already improved.
Please check it.

**Pull request merged**
